/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBifile: typeof import('~icons/bi/file')['default']
    IBisave: typeof import('~icons/bi/save')['default']
    IBitrash: typeof import('~icons/bi/trash')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
  }
}
